# -*- coding: utf-8 -*-
"""Oasis_Task2_Unemployment Analysis with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vw_e-gTYo2LmEGtdMU2VvPdc51ECyqMO
"""

# Import necessary libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv("Unemployment_Rate_upto_11_2020.csv")

# Clean column names
df.columns = df.columns.str.strip()
df.rename(columns={
    "Date": "Date",
    "Estimated Unemployment Rate (%)": "Unemployment Rate",
    "Estimated Employed": "Employed",
    "Estimated Labour Participation Rate (%)": "Labour Participation Rate",
    "Region": "State",
    "Region.1": "Zone"
}, inplace=True)

# Convert 'Date' to datetime format
df["Date"] = pd.to_datetime(df["Date"], dayfirst=True)

# Set Seaborn style
sns.set(style="whitegrid")

# PLOT 1: National Trend Over Time
plt.figure(figsize=(14, 6))
sns.lineplot(data=df, x="Date", y="Unemployment Rate", ci=None)
plt.title("Unemployment Rate in India Over Time", fontsize=16)
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# PLOT 2: Average Unemployment by State
plt.figure(figsize=(14, 8))
state_avg = df.groupby("State")["Unemployment Rate"].mean().sort_values(ascending=False)
sns.barplot(x=state_avg.values, y=state_avg.index, palette="coolwarm")
plt.title("Average Unemployment Rate by State", fontsize=16)
plt.xlabel("Average Unemployment Rate (%)")
plt.ylabel("State")
plt.tight_layout()
plt.show()

#  PLOT 3: Zone-wise Unemployment Trend
plt.figure(figsize=(14, 6))
sns.lineplot(data=df, x="Date", y="Unemployment Rate", hue="Zone")
plt.title("Zone-wise Unemployment Trends", fontsize=16)
plt.xlabel("Date")
plt.ylabel("Unemployment Rate (%)")
plt.xticks(rotation=45)
plt.legend(title="Zone")
plt.tight_layout()
plt.show()

#  PLOT 4: Heatmap - Unemployment by State and Date
pivot_table = df.pivot_table(values="Unemployment Rate", index="State", columns="Date")
plt.figure(figsize=(16, 10))
sns.heatmap(pivot_table, cmap="YlOrRd", linewidths=0.5)
plt.title("Heatmap of Unemployment Rate by State and Date", fontsize=16)
plt.xlabel("Date")
plt.ylabel("State")
plt.tight_layout()
plt.show()

